---
title: "Fantacy Craft application"
author: "Constantinos Yeles"
todate: "`r format(Sys.time(), '%a_%b_%d_%Y')`"
output:
  pdf_document: default
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---
## load libraries
```{r load libraries}
suppressPackageStartupMessages({
  library('tidyverse')
  library('data.table')
  library("shiny")
  library("colourpicker")
})
```
## add todate
```{r todate_of_analysis}
todate <- format(Sys.time(), "%d_%b_%Y")
```
## tables we need
```{r}
species <- readxl::read_xlsx("FC_tables/Species.xlsx")
talents <- readxl::read_xlsx("FC_tables/Talents.xlsx")
specialties <- readxl::read_xlsx("FC_tables/Specialties.xlsx")
Attr_sum <- readxl::read_xlsx("FC_tables/Attributes/Attributes_summary.xlsx")
Attr_sum_sc <- readxl::read_xlsx("FC_tables/Attributes/Attributes_scores.xlsx")
Attr_scores <- readxl::read_xlsx("FC_tables/Attributes/Attributes_system.xlsx")
```
## functions we need
```{r}
# select the attribute scores----
## provide the count of each value you can use
## to put as an attribute
Attr_score_select <- function(y){
  Attr_scores %>% 
    .[y,] %>% 
    pivot_longer(-scope) %>% 
    count(value)
}

## change the number of the score you still have
Attr_score_remove <- function(df, score){
    df %>% 
        mutate(n = ifelse(value == score, n-1, n)) %>% 
        mutate(n = ifelse(n == 0, NA, n)) %>% 
        drop_na()  
}

```

## character final tables
```{r}
Attrb_main <- tribble(
  ~Strength, ~Dexterity, ~Constitution, ~Intelligence, ~Wisdom, ~Charisma,
  0,0,0,0,0,0
)


for(z in species$Species){
test1 <- species %>% 
  filter(Species == z) %>% 
  t() %>% 
  as_tibble(rownames = "Info") %>% 
  filter(!V1 == "No",!V1 == 0) %>% 
  deframe() %>% 
  data.frame() %>% 
  t() %>% 
  as_tibble()

map2( 
  .x = names(test1)[names(test1) %>% str_detect("Attr_")],
  .y = names(test1)[names(test1) %>% str_detect("Attr_")] %>% 
    str_replace("r_","_Score_"), 
  ~ test1 %>% 
    add_column(!!test1[[.x]] := test1[[.y]],.before = "Species")) %>% 
  reduce(bind_cols) %>%
   select(
     -c(Species1:!!str_c(names(test1)[length(names(test1))],"1")),
     -c(!!names(test1)[str_detect(names(test1),"Attr_")][1]:!!str_replace(names(test1)[str_detect(names(test1),"Attr_")][2],"r_","_Score_")) ) %>% 
  select(length(.),everything()) %>% 
   t() %>% 
  as_tibble(rownames = "Info") 
}

map(species$Species,~ ran_F1
)

#as_tibble(cbind(nms = names(test1), t(test1)))
```
## ui
```{r}
ui <- fluidPage(
   theme = shinythemes::shinytheme("superhero"),
    titlePanel("Create your Character:"), 
  navlistPanel(
    "Step 0: Concept",
    tabPanel("Character Info",
      textInput("ch_name","Enter character name: ", "Manohar"),
      textInput("player", "Enter player name: ", "My name")),
    
    tabPanel("Basic Characteristics",
      sliderInput("ch_age", "Select the age of your character:",
                min = 18, max = 100,
                value = c(25), pre = "years "),
      
      selectInput("ch_gender", "Select character gender: ",
                choices = c("Female", "Male", "Non applicable")),
    
      colourInput("ch_eyes", "Select character eye color", "brown",
                              palette = "limited",
                              showColour = "background"),
      
      colourInput("ch_hair", "Select character hair color", "black",
                              palette = "limited",
                              showColour = "background"),
      
      numericInput("ch_xp", "Select the xp of your character:",
                 value = 0, min = 0, max = 600000),
      
      sliderInput("ch_height", "Select character height:",
                 value = 10, min = 10, max = 600, pre = "cm "),
      
      sliderInput("ch_weight", "Select character weight: ",
                 value = 1, min = 1, max = 99999, pre = "g ")
      ),
   
   "Step 1: Attributes",
    tabPanel("Main Attributes",
      sidebarPanel(
     "Attributes",   
        
        # select the values for each attr
    c("Strength_ui", "Dexterity_ui",
     "Constitution_ui","Intelligence_ui",
      "Wisdom_ui","Charisma_ui") %>% 
          map(~uiOutput(.x))
      ),
      mainPanel( 
       # table with Attributes score
       h4("Select the row with the Attribute scores for your character:"),
       DT::dataTableOutput("table"))
      ),
    
    "Step 2: Origin",
    tabPanel("Species",
       sidebarPanel(
         selectInput("ch_Species", "Select character species: ",
                choices = species$Species),
         conditionalPanel(
           condition = "input.ch_Species == 'Human'",
           selectInput("ch_Talent", "Select character Talent: ",
             choices = talents$Talent)
           )
         ),
      mainPanel(
        # table with Species Info
       h4("Information about the species of your character:"),
       DT::dataTableOutput("table_species")
      )
      ),
     tabPanel("Specialty",
       sidebarPanel(
      selectInput("ch_Species", "Select character species: ",
                choices = specialties$Specialty)),
       mainPanel(
         
       )
       ),
    "-----",
    tabPanel("Component 5")
  )
)


```
## server1
```{r}
 spec_test <- reactive(input$ch_Species)
  if(spec_test() == "Human" ){
  output$Talents = renderUI(
    selectInput("ch_Talents", "Select character talent: ",
                choices = talents$Talent)
  )
  }


Scores <- list(
  "Strength_ui",
  "Dexterity_ui",
  "Constitution_ui",
  "Intelligence_ui",
  "Wisdom_ui",
  "Charisma_ui"
) %>% set_names(.)

Scores_output <- list(
  "Strength_ui",
  "Dexterity_ui",
  "Constitution_ui",
  "Intelligence_ui",
  "Wisdom_ui",
  "Charisma_ui"
) %>% set_names(.)
Scores_output[[1]] <- Attr_score_select(1)

server <- function(input, output) {
  
  output$table <- DT::renderDataTable(
    DT::datatable(
      data = Attr_scores, 
      style = 'bootstrap', 
      options = list(pageLength = 10),
      selection = "single"))
  Scores[["Strength_ui"]] <- reactive(
  
    Attr_score_select(input$table_row_last_clicked))
    
  test_f_1<- function(x,y){
    Scores_output[[!!.y + 1]]  :=  Attr_score_remove(Scores_output[[.x]], 13)
  }
 
  
  
  imap(Scores_output,
    .x[[!!!.y +1]] := .x %>% Attr_score_remove( 13))

   imap(my_list, my_list[[.y +1]] <- .x %>% +1)

  
  map(.x = 1:4,
    .f = as.data.table(Scores_output[[!!.x]]) := as.data.table(Scores_output[[!!.x -1]])%>% Attr_score_remove( 13)
  )
  
  
  pmap(..1 = names(Scores)[1:5], 
    ..2 = names(Scores)[1:5] %>% seq_along(),
    ..3 = c("Strength_1","Dexterity_1",
      "Constitution_1","Intelligence_1",
      "Wisdom_1"),
  .f = ~ function(x, y, z){
    output[[..1]] <- renderUI({
      selectInput(..3,
        label = str_c("Choose",str_remove(..1,"_ui") ,
          "score for your character:"),
        c(Choose='',as.character(Scores[[..1]]()$value))
        )
      })
   Scores[[..2 +1]] <- reactive(Scores[[..1]]() %>%
                        Attr_score_remove(input[[..3]]))
    }
  )
   #Charisma
  output$Charisma_ui = renderUI(
  selectInput('Charisma_1', 
              label = "Choose 'Charisma score for your character:", 
              c(Choose='', 
                as.character(Scores5()$value))
    )
  )
  
}

  


 

```


## server
```{r}
server <- function(input, output) {
  output$table <- DT::renderDataTable(
    DT::datatable(
      data = Attr_scores, 
      style = 'bootstrap', 
      options = list(pageLength = 10),
      selection = "single"))
  
species_tb_1 <- reactive({
  species %>%
       filter(Species == input$ch_Species) %>%
       t() %>%
       as_tibble(rownames = "Info") %>%
       filter(!V1 == "No",!V1 == 0) %>%
       deframe() %>%
       data.frame() %>%
       t() %>%
       as_tibble()
})

species_tb_Info <-  reactive({
  map2(
      .x = names(species_tb_1())[names(species_tb_1()) %>% str_detect("Attr_")],
      .y = names(species_tb_1())[names(species_tb_1()) %>% str_detect("Attr_")] %>% 
    str_replace("r_","_Score_"), 
    ~ species_tb_1() %>% 
    add_column(!!species_tb_1()[[.x]] := species_tb_1()[[.y]],.before = "Species")) %>%
    reduce(bind_cols) %>%
    select(
     -c(Species1:Extra_61),
     -c(!!names(species_tb_1())[str_detect(names(species_tb_1()),"Attr_")][1]:!!str_replace(names(species_tb_1())[str_detect(names(species_tb_1()),"Attr_")][2],"r_","_Score_")) ) %>% 
  select(length(.),everything()) %>% 
   t() %>% 
  as_tibble(rownames = "Info") 
})   
  output$table_species <- DT::renderDataTable(
    DT::datatable(
      data = species_tb_Info(), 
      style = 'bootstrap', 
      options = list(pageLength = 10),
      selection = 'none'))
  
  Scores <- reactive(Attr_score_select(input$table_row_last_clicked))
  
  output$Strength_ui <- renderUI({
    #Strength
           selectInput('Strength_1', 
                       label = "Choose Strength score for your character:", 
                       c(Choose='', 
                         as.character(Scores()$value))
           )
  })
  Scores1 <- reactive(Scores() %>%
                        Attr_score_remove(input$Strength_1))
  #Dexterity
  output$Dexterity_ui = renderUI(
    selectInput('Dexterity_1',
                label = "Choose Dexterity score for your character:",
                c(Choose='', as.character(Scores1()$value))
    )
  )
  Scores2 <- reactive(Scores1() %>%
                        Attr_score_remove(input$Dexterity_1))
  #Constitution
  output$Constitution_ui = renderUI(
    selectInput('Constitution_1',
                label = "Choose Constitution score for your character:",
                c(Choose='', as.character(Scores2()$value))
    )
  )
  Scores3 <- reactive(Scores2() %>%
                        Attr_score_remove(input$Constitution_1))
  #Intelligence
  output$Intelligence_ui = renderUI(
  selectInput('Intelligence_1', 
              label = "Choose Intelligence score for your character:", 
              c(Choose='', as.character(Scores3()$value) )
    )
  )
  Scores4 <- reactive(Scores3() %>%
                        Attr_score_remove(input$Intelligence_1))
  #Wisdom
  output$Wisdom_ui = renderUI(
  selectInput('Wisdom_1', 
              label = "Choose 'Wisdom score for your character:", 
              c(Choose='', as.character(Scores4()$value) )
              )
  )
  Scores5 <- reactive(Scores4() %>%
                        Attr_score_remove(input$Wisdom_1))
  #Charisma
  output$Charisma_ui = renderUI(
  selectInput('Charisma_1', 
              label = "Choose 'Charisma score for your character:", 
              c(Choose='', 
                as.character(Scores5()$value))
    )
  )
 
  
  
  
}
```
## run the app
```{r}

shinyApp(ui = ui, server = server)

```

