---
title: "Make the functions for the chars"
subtitle: "?????"
author: "Constantinos Yeles (Konstantinos Geles)"
date: "`r format(Sys.time(), '%a_%b_%d_%Y')`"
output:
  pdf_document:
    toc: yes
    toc_depth: 3
  html_document:
    toc: yes
    toc_depth: 3
    theme: paper 
editor_options:
  chunk_output_type: console
---

## libraries
```{r}
library(dplyr)
library(tidyr)
library(magrittr)
library(stringr)
library(tibble)
library(purrr)
```


## tables we need
### species info
```{r}

species <- readxl::read_xlsx("FC_tables/Species.xlsx")

# pick species general characteristics
species_gen <- species %>% 
  select(!starts_with(c("Att","Extr")))

# pick species Attributes
species_Att <- species %>% 
  select(Species, starts_with("Att")) %>% 
  pivot_longer(cols = starts_with("Attr_"), 
               names_to = "Attr_Value", values_to = "Attribute") %>% 
  pivot_longer(cols = starts_with("Att_Score"), 
               names_to = "Score_Value", values_to = "score") %>%
  filter(Attribute != "No") %>% 
  mutate(Attr_Value = Attr_Value %>% str_remove("Attr_") %>% as.integer(),
         Score_Value = Score_Value %>% str_remove("Att_Score_") %>% as.integer()) %>% 
  filter(Attr_Value == Score_Value) %>% 
  select(-c(Attr_Value, Score_Value)) %>%
  separate_rows(Attribute)

# pick species extra abilities
species_Ext <- species %>% 
  select(Species, starts_with("Extr")) %>% 
  pivot_longer(cols = c(Extra_1:Extra_10)) %>% 
  filter(!value == "No") %>% 
  select(-name)
```

### talents info
```{r}
talents <- readxl::read_xlsx("FC_tables/Talents.xlsx")

# pick talents general characteristics
talents_gen <- talents %>% 
  select(!starts_with(c("Attri", "Modi", "Benef")))

# pick talents Attributes
talents_Att <- talents %>% 
  select(Talent, starts_with(c("Attri", "Modi"))) %>% 
  pivot_longer(cols = starts_with("Attr"), 
               names_to = "Attr_Value", values_to = "Attribute") %>% 
  pivot_longer(cols = starts_with("Mod"), 
               names_to = "Score_Value", values_to = "score") %>%
  filter(Attribute != "No") %>% 
  mutate(Attr_Value = Attr_Value %>% str_remove("Attribute_") %>% as.integer(),
         Score_Value = Score_Value %>% str_remove("Modifier_") %>% as.integer()) %>% 
  filter(Attr_Value == Score_Value) %>% 
  select(-c(Attr_Value, Score_Value))

# pick talents Benefits
talents_Benef <- talents %>% 
  select(Talent, starts_with("Benef")) %>% 
  pivot_longer(cols = starts_with("Benef"), 
               names_to = "Benefit_value", values_to = "Benefit") %>% 
  filter(Benefit != "No") %>% 
  select(!Benefit_value)
```

### specialties info
```{r}
specialties <- readxl::read_xlsx("FC_tables/Specialties.xlsx")

# pick specialties general characteristics
specialties_gen <- specialties %>% 
  select(!starts_with("Extra")) 

# pick specialties extra abilities
specialties_extra <- specialties %>% 
  select(Specialty, starts_with("Extra")) %>% 
  pivot_longer(cols = starts_with("Extra"), 
               names_to = "specialties_values", values_to = "Extra") %>% 
  filter(Extra != "No") %>% 
  select(!specialties_values)
```
 
### Attributes information and table
```{r}
Attr_sum <- readxl::read_xlsx("FC_tables/Attributes/Attributes_summary.xlsx")
Attr_sum_sc <- readxl::read_xlsx("FC_tables/Attributes/Attributes_scores.xlsx") %>% mutate(Cost = as.numeric(Cost))
Attr_scores <- readxl::read_xlsx("FC_tables/Attributes/Attributes_system.xlsx")

# Attr_scores  %>% pivot_longer(-scope) %>% left_join(Attr_sum_sc, by = c("value" = "Score"))
# Attr_scores  %>% pivot_longer(-scope) %>% left_join(Attr_sum_sc, by = c("value" = "Score")) %>% group_by(scope) %>% summarize(across(.cols = where(is.numeric), .fns = ~ sum(.x, na.rm = TRUE))) %>% arrange(desc(value, Modifier)) %>% left_join(Attr_scores)
```

### Attributes pick table
Check all different combinations for the starting values of Attributes
```{r}

cost_values <- Attr_sum_sc %>% drop_na()

attr_pick <- function(perm, cost_v = cost_values, attr_total_cost = 36){
  
  my_selected_values <- slice_sample(cost_values, n = 6, replace = TRUE)
  
  Attr_total_cost <- my_selected_values %>% summarise(sum_cost = sum(Cost)) %>% pull(sum_cost)
  
  Attr_total_mod <- my_selected_values %>% summarise(mod_res = sum(Modifier)) %>% pull(mod_res)
  
  result_tbl <- my_selected_values %>% mutate(Cost_sum = sum(Cost), Mod_sum = sum(Modifier))
                                              
  ifelse(test = (Attr_total_cost == attr_total_cost) & (Attr_total_mod < 6), 
         yes = return(result_tbl),
         no = return(attr_pick()))
  }

tic()
first_test <- map_dfr(str_c("dat", 1:100) %>% set_names, attr_pick, .id = "Passed_sets")
toc()

best_sets_1 <- first_test %>% 
  mutate(Passed_sets = str_remove(Passed_sets,"dat") %>% as.numeric() ) %>% 
  select(-c(Cost, Modifier)) %>% 
  arrange(Passed_sets, desc(Score)) %>% 
  mutate(Attr = rep(c("Str", "Dex", "Con", "Int", "Wis", "Cha" ), 100)) %>% 
  pivot_wider(names_from = "Attr", values_from = "Score") %>% 
  arrange(desc(Mod_sum)) %>% 
  distinct(Str, Dex, Con, Int, Wis, Cha, .keep_all = TRUE)

best_sets %>% vroom::vroom_write("best_attrib_values_sets.txt")
#old_best_sets <- vroom::vroom("best_attrib_values_sets.txt")

# use multiple procs
library(furrr)
plan(multisession, workers = 4)

tic()
third_test <- future_map_dfr(str_c("dat", 1:100) %>% set_names, attr_pick, .id = "Passed_sets")
toc()

best_sets_2 <- second_test %>% 
  mutate(Passed_sets = str_remove(Passed_sets,"dat") %>% as.numeric() ) %>% 
  select(-c(Cost, Modifier)) %>% 
  arrange(Passed_sets, desc(Score)) %>% 
  mutate(Attr = rep(c("Str", "Dex", "Con", "Int", "Wis", "Cha" ), 100)) %>% 
  pivot_wider(names_from = "Attr", values_from = "Score") %>% 
  arrange(desc(Mod_sum)) %>% 
  distinct(Str, Dex, Con, Int, Wis, Cha, .keep_all = TRUE)

best_sets_3 <- third_test %>% 
  mutate(Passed_sets = str_remove(Passed_sets,"dat") %>% as.numeric() ) %>% 
  select(-c(Cost, Modifier)) %>% 
  arrange(Passed_sets, desc(Score)) %>% 
  mutate(Attr = rep(c("Str", "Dex", "Con", "Int", "Wis", "Cha" ), 100)) %>% 
  pivot_wider(names_from = "Attr", values_from = "Score") %>% 
  arrange(desc(Mod_sum)) %>% 
  distinct(Str, Dex, Con, Int, Wis, Cha, .keep_all = TRUE)

### 1000 test
tic()
fourth_test <- future_map_dfr(str_c("dat", 1:1000) %>% set_names, attr_pick, .id = "Passed_sets")
toc()

best_sets_4 <- fourth_test %>% 
  mutate(Passed_sets = str_remove(Passed_sets,"dat") %>% as.numeric() ) %>% 
  select(-c(Cost, Modifier)) %>% 
  arrange(Passed_sets, desc(Score)) %>% 
  mutate(Attr = rep(c("Str", "Dex", "Con", "Int", "Wis", "Cha" ), 1000)) %>% 
  pivot_wider(names_from = "Attr", values_from = "Score") %>% 
  arrange(desc(Mod_sum)) %>% 
  distinct(Str, Dex, Con, Int, Wis, Cha, .keep_all = TRUE)

tic()
fifth_test <- future_map_dfr(str_c("dat", 1:1000) %>% set_names, attr_pick, .id = "Passed_sets")
toc()

best_sets_5 <- fifth_test %>% 
  mutate(Passed_sets = str_remove(Passed_sets,"dat") %>% as.numeric() ) %>% 
  select(-c(Cost, Modifier)) %>% 
  arrange(Passed_sets, desc(Score)) %>% 
  mutate(Attr = rep(c("Str", "Dex", "Con", "Int", "Wis", "Cha" ), 1000)) %>% 
  pivot_wider(names_from = "Attr", values_from = "Score") %>% 
  arrange(desc(Mod_sum)) %>% 
  distinct(Str, Dex, Con, Int, Wis, Cha, .keep_all = TRUE)

# collapse all sets and distinct them

all_sets <- bind_rows(old_best_sets, best_sets_2, 
                      best_sets_3, best_sets_4, 
                      best_sets_5, .id = "set") %>% 
  arrange(desc(Mod_sum)) %>% 
  distinct(Str, Dex, Con, Int, Wis, Cha, .keep_all = TRUE)

all_sets %>% 
  rename_with(Str:Cha, .fn = ~str_c("A", 1:6)) %>% 
  vroom::vroom_write("FC_tables/Attributes/best_Attributes_system_sets.txt")
#all_sets <- vroom::vroom("FC_tables/Attributes/best_Attributes_system_sets.txt")
#######
#library(particions)
#library(iterpc)restrictedparts()
```


## Functions
### Attr_score_select Fucntion, to get the Attributes
```{r}
## provide the count of each value you can use
## to put as an attribute
Attr_score_select <- function(att = "Sel1"){
  Attr_scores %>% 
    filter(scope == att) %>% 
    pivot_longer(-scope) %>% 
    count(value)
}

## change the number of the score you still have 
## (an interactive function for later)
Attr_score_remove <- function(df, score){
    df %>% 
    mutate(n = ifelse(value == score, n-1, n)) %>% 
    drop_na()
}
```

### character_description Function
```{r}
##character creation
character_description <- list(
                  Name = "Name",
                  Surname = "sName",
                  Nickname = "ncname",
                  Player = "player name",
                  Gender = "Male or Female",
                  Age = "25 years",
                  Height = 180,
                  Weight = 90,
                  Hair = "Black",
                  Eyes = "Blue")
```

### character_origin Function
```{r}
character_origin <- list(
               Species = "species",
               Talent = "a talent",
               Specialty = "a specialty",
               Size = "M",
               Space = "1x1",
               Reach = 1,
               Wounds = 1.00,
               Ground_speed = 30)
```


```{r}
get_initial_attrb <- function(x = "Sas_1", init_table = Attr_scores){
  init_attr_vector <- init_table %>% 
    filter(SAS == x) %>% 
    pivot_longer(-SAS) %>% 
    slice_sample(n = 6) %>% 
    pull(value)
  
  return(init_attr_vector)
}

Main_char_Attrb <- Attr_sum %>% 
  add_column(Score = get_initial_attrb(x = "Sas_13")) %>% 
  left_join(Attr_sum_sc)

## get Attrb
get_r_attrb <- function(){
  Random_attrbs <- Attr_scores %>%
  slice_sample() %>% 
  pivot_longer(-scope) %>% 
  slice_sample(n = 6) %>% 
  pull(value)
  
  return(Random_attrbs)
}

get_r_origin <- function(){
  origin_species <- list()
  
  origin_species$general <- species_gen %>%
  slice_sample()
  
  origin_species$species_attrb <- species_Att %>%
  filter(Species == pull(origin_species$general, Species))
  
  origin_species$extras<- species_Ext %>%
  filter(Species == pull(origin_species$general, Species))
  
  if (pull(origin_species$general, Species) == "Human") {
    
  }
  return(origin_species)
}


Random_Character <- function(){
  Attributes <- tibble(Attr_sum, Attrb_main = get_r_attrb())
  return(Attributes)
}
```

## character final tables